### ISSUE TITLE
Pixel 8 pro - No notifications

### ISSUE THREAD

**Issue by ghost** [carlonluca/flashbackprism#1] opened 2024-03-12 13:21 UTC
First of all thank you very much for this App!
I'm using it on my Pixel 8 pro, the service is running in the background but I don't receive notifications. Android says the app does not send any (see Screenshot). 
![Screenshot_20240312-142026](https://github.com/carlonluca/flashbackprism/assets/124933490/fbcf9c3f-bd8b-4d76-80ef-3d274754b013)

**Comment by carlonluca** [comment] 2024-03-12 18:23
Hello, the app sends notifications only when the server returns photos for the current day. Do you see the photos when you open the interface?

**Comment by ghost** [comment] 2024-03-12 18:31
Hey,

when I open the app I do see the photos, yes.

**Comment by carlonluca** [comment] 2024-03-12 19:14
What Android version are you running? 14?

**Comment by ghost** [comment] 2024-03-12 19:52
Yes, sorry its Android 14. App / service is running in background

**Comment by carlonluca** [comment] 2024-03-17 15:24
Can you test version 0.5.0?

**Comment by ghost** [comment] 2024-03-17 15:44
Will do! First glance looks better already. Service is running and asked whether it could send me notifications.

**Comment by ghost** [comment] 2024-03-18 08:48
> Can you test version 0.5.0?

Well this version works almost too well.. I get the notification that new flasbacks are available continously.
I click on it, it goes away, comes back later :)

If I may add: Now I get an icon in the taskbar. It would be great if that could be an option (to turn off) :)

**Comment by carlonluca** [comment] 2024-03-18 12:42
Thanks for your feedback.

Are you sure it goes away clicking on it? I have to remove it manually on my device.

**Comment by ghost** [comment] 2024-03-18 14:39
I tried both clicking and swiping. Was gone both times then came back later. It stopped coming back after a couple of hours though.

**Comment by carlonluca** [comment] 2024-03-18 17:59
I tried to reproduce this somehow, no luck so far.

**Comment by ghost** [comment] 2024-03-18 20:13
I will check the next days how it behaves and report back. Anything I should check specifically?

**Comment by carlonluca** [comment] 2024-03-18 23:24
The notification should arrive around 8 o'clock in the morning, local time. This should clearly be configurable but, at the moment, there is no page to do so. It won't be precise, it may even be 8:30.
For me, the notification remains until I explicitly remove it. It may not be desirable, not sure. The notification should clearly not repeat.

I'll also pay attention to this tomorrow: it may be possible that I did not notice the notification was sent multiple times because I tend to leave it there.

Thanks for your help!

**Comment by ghost** [comment] 2024-03-19 11:54
Thank YOU for the app! Today everything worked as intended / described.
Notification had to be swiped away and didn't come back.

Is there anything to be done about the icon in the taskbar? And one other question: how does the app fetch he pictures? Just the thumbnails (which can be cached on a SSD) or the pictures themselves?

**Comment by carlonluca** [comment] 2024-03-19 18:40
> Thank YOU for the app! Today everything worked as intended / described.

Very well.

> Is there anything to be done about the icon in the taskbar?

Can you explain the question better?

> And one other question: how does the app fetch he pictures?

It should do this more or less like the webapp. Smaller-sized previews for the grids, and the full image when displaying the images in fullscreen.

**Comment by ghost** [comment] 2024-03-19 20:00
Of course, sorry I will try to explain better.
As far as I understand the app uses the Flashback service "app" to stay permantly in the background. For me that means the App leaves a permanent icon in the taskbar. Some apps give an option to hide that icon and / or hide the notification all together. Android 14 with the Pixel shows me permanently running apps in a separate menu "active apps",so I would not need the notification ( I think). If I turn the notification off on the settings of Android I will not be notified at all, because it doesn't have the permission to send any notifications.
Does that help?

Regarding my other question: I am investigating what processes wake up my disks (which store the pictures but not the thumbnails). There was a time based correlation with the app. I don't think it was the "culprit" though

**Comment by carlonluca** [comment] 2024-03-19 21:52
I did not test this, as I'm currently leaving the permanent notification for the moment, but my understanding is that this should be possible. In the application settings, there is a section called "notifications". Inside that section you should see two entries. One marked as "notifier" and one marked as "monitor". The monitor is the notification for the service. That is what you want to hide. The notifier should instead be the daily notification, which you want to leave enabled.

Implemented but never tested.

> Regarding my other question: I am investigating what processes wake up my disks (which store the pictures but not the thumbnails). There was a time based correlation with the app. I don't think it was the "culprit" though

I have to be sincere: I wrote the app very quickly just for myself, I did not go into this level of optimization, sorry. However, from what I can remember, the service does not download images, it just queries the database and receives information without image data. Smaller previews are downloaded when you open the app. The entire image only when the fullscreen view is opened.

**Comment by ghost** [comment] 2024-03-20 07:30
Good news on all fronts:
Hiding monitor worked, I still got the notification and it did not come back after swiping.
Your explanation of how the app works seem plausible, as my Server HDDs did not wake even though quite a lot of pictures where fetched.

Thank you again for this wonderful app. Is there any way you could try a PR to integrate the function in photoprism by any chance?

**Comment by carlonluca** [comment] 2024-03-20 12:46
Photoprism did not seem to have an official Android app. They said they are however going to implement this at some point.

**Closed as completed by carlonluca** 2024-03-20 12:46 UTC
